# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deeprelay < Formula
  desc "deeprelay command-line interface — OpenAI-compatible serverless inference from your terminal."
  homepage "https://deeprelay.ai"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deeprelay-dev/deeprelay-cli/releases/download/v1.1.0/deeprelay_1.1.0_darwin_amd64.tar.gz"
      sha256 "fd3c216c57327f89011f47d0c0f76b7fceb680371ca08e94ab13d7e9c303c037"

      define_method(:install) do
        bin.install "deeprelay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deeprelay-dev/deeprelay-cli/releases/download/v1.1.0/deeprelay_1.1.0_darwin_arm64.tar.gz"
      sha256 "9a6d46d9ece779453811bfc6ab5160b32b2c536cd729a34efb3dd11ac4644571"

      define_method(:install) do
        bin.install "deeprelay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deeprelay-dev/deeprelay-cli/releases/download/v1.1.0/deeprelay_1.1.0_linux_amd64.tar.gz"
      sha256 "e38885cecd98c079fc2c9cafbabefd83179e1ead17de071441dedbf10e24adc5"
      define_method(:install) do
        bin.install "deeprelay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deeprelay-dev/deeprelay-cli/releases/download/v1.1.0/deeprelay_1.1.0_linux_arm64.tar.gz"
      sha256 "47a667c9d4c22cda79569fc01713f695e2de91a1602ab44a471353ff1c3b6f10"
      define_method(:install) do
        bin.install "deeprelay"
      end
    end
  end

  test do
    system "#{bin}/deeprelay", "--version"
  end
end
